name: Retrieve AWS Secrets information
run-name: ${{ github.actor }} is doing workflow testrun

on:
  push:
    branches:  [ main, "*" ]

jobs:
  pre-deploy:
    runs-on: ubuntu-latest

  install-dependencies:
    runs-on: ubuntu-latest
    needs: pre-deploy
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run Installation of Dependencies Commands
        run: npm install

  get-secrets:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Get secrets
        run: aws-secretsmanager get-secrets-value --secret-id rudyn-secret-test
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  